/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import Algorithms.AStar;
import Algorithms.BFS;
import Image.ImageDiscretizer;
import Algorithms.DFS;
import graph.search.DisplayGraph;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author Diego Jacobs
 */
public class Principal extends javax.swing.JFrame {
    private int size;
    private File image;
    private BufferedImage imageDiscretized;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        jLabel2.setVisible(false);
        jLabel3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        uploadButton = new javax.swing.JButton();
        resizeNTextField = new javax.swing.JTextField();
        discretizeButton = new javax.swing.JButton();
        bfsButton = new javax.swing.JButton();
        dfsButton = new javax.swing.JButton();
        aStarButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        uploadButton.setText("Upload");
        uploadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadButtonActionPerformed(evt);
            }
        });

        discretizeButton.setText("Discretizar");
        discretizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discretizeButtonActionPerformed(evt);
            }
        });

        bfsButton.setText("BFS");
        bfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bfsButtonActionPerformed(evt);
            }
        });

        dfsButton.setText("DFS");
        dfsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dfsButtonActionPerformed(evt);
            }
        });

        aStarButton.setText("A*");
        aStarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aStarButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("N:");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhattan", "Breaking Ties" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(uploadButton)
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resizeNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(discretizeButton)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(408, 408, 408)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(302, 302, 302)
                        .addComponent(bfsButton)
                        .addGap(73, 73, 73)
                        .addComponent(dfsButton)
                        .addGap(61, 61, 61)
                        .addComponent(aStarButton)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(discretizeButton)
                        .addComponent(resizeNTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addComponent(uploadButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 506, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dfsButton)
                    .addComponent(bfsButton)
                    .addComponent(aStarButton)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void uploadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadButtonActionPerformed
        // TODO add your handling code here:
        String path = System.getProperty("user.dir");
        JFileChooser fileChooser = new JFileChooser(path);
        int returnValue = fileChooser.showOpenDialog(null);
        
        if(returnValue == JFileChooser.APPROVE_OPTION){
            this.image = fileChooser.getSelectedFile();
            
            try {
                BufferedImage originalBufferedImage = ImageIO.read(this.image);
                ImageIcon icon = new ImageIcon(originalBufferedImage);
                jLabel2.setIcon(icon);
                jLabel2.setVisible(true);
                jLabel2.setText("");
            } catch (IOException ex) {
                Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_uploadButtonActionPerformed

    private void discretizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discretizeButtonActionPerformed
        // TODO add your handling code here:
        if(!image.equals(null)){
            if(!resizeNTextField.getText().isEmpty()){
                this.size = Integer.parseInt(resizeNTextField.getText());
                ImageDiscretizer imageDiscretizer = new ImageDiscretizer(this.image, this.size);
                imageDiscretized = imageDiscretizer.getImageDiscretized();
                ImageIcon icon = new ImageIcon(imageDiscretized);
                jLabel3.setIcon(icon);
                jLabel3.setVisible(true);
                jLabel3.setText("");
            }
        }
    }//GEN-LAST:event_discretizeButtonActionPerformed

    private void bfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bfsButtonActionPerformed
        // TODO add your handling code here:
        ImageDiscretizer imageDiscretizer = new ImageDiscretizer(image, size);
        BFS bfs = new BFS(size, size, imageDiscretizer.getImageDiscretized());
        bfs.Solve();
        
        JFrame window = new JFrame();
        window.setSize(400, 400);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setTitle("BFS Solution");
        window.add(new DisplayGraph(size, size, imageDiscretizer.getImageDiscretized(), bfs.getGraph(), bfs.getFinalPath()));
    }//GEN-LAST:event_bfsButtonActionPerformed

    private void dfsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dfsButtonActionPerformed
        // TODO add your handling code here:
        ImageDiscretizer imageDiscretizer = new ImageDiscretizer(image, size);
        DFS dfs = new DFS(size, size, imageDiscretizer.getImageDiscretized());
        dfs.Solve();
        
        JFrame window = new JFrame();
        window.setSize(400, 400);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setTitle("DFS Solution");
        window.add(new DisplayGraph(size, size, imageDiscretizer.getImageDiscretized(), dfs.getGraph(), dfs.getFinalPath()));
    }//GEN-LAST:event_dfsButtonActionPerformed

    private void aStarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aStarButtonActionPerformed
        // TODO add your handling code here:
        int type = jComboBox1.getSelectedIndex() + 1;
        ImageDiscretizer imageDiscretizer = new ImageDiscretizer(image, size);
        AStar aStar = new AStar(size, size, imageDiscretizer.getImageDiscretized());
        aStar.Solve(type);
        
        JFrame window = new JFrame();
        window.setSize(400, 400);
        window.setLocationRelativeTo(null);
        window.setVisible(true);
        window.setTitle("A* Solution");
        window.add(new DisplayGraph(size, size, imageDiscretizer.getImageDiscretized(), aStar.getGraph(), aStar.getFinalPath()));
    }//GEN-LAST:event_aStarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aStarButton;
    private javax.swing.JButton bfsButton;
    private javax.swing.JButton dfsButton;
    private javax.swing.JButton discretizeButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField resizeNTextField;
    private javax.swing.JButton uploadButton;
    // End of variables declaration//GEN-END:variables
}
